name: Portfolio Deployment

on:
  push:
    branches:
    - main
env:
  AWS_Region: "ap-south-1"    
permissions:
  id-token: write
  contents: read
jobs:
  DEMO-OIDC:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::851725202832:role/oidc
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_Region }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://oidc-cc --delete
